<?php

try {
    $a = Foo::bar();
} catch (\Exception $ex) { }